
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 28 13:01:56 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 40;
  public static final int NUMCONST = 23;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 32;
  public static final int MINUS = 14;
  public static final int RPAREN = 7;
  public static final int GRE = 36;
  public static final int AND = 19;
  public static final int RECORD = 47;
  public static final int OR = 18;
  public static final int COMMA = 8;
  public static final int CLASS = 41;
  public static final int INC = 44;
  public static final int DIV = 16;
  public static final int PLUS = 11;
  public static final int IF = 27;
  public static final int EXP = 20;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 46;
  public static final int error = 1;
  public static final int MUL = 15;
  public static final int GEA = 37;
  public static final int MOD = 17;
  public static final int BREAK = 31;
  public static final int IDENT = 26;
  public static final int VOID = 13;
  public static final int EQU = 34;
  public static final int NEQU = 35;
  public static final int LBRACE = 3;
  public static final int ELSE = 28;
  public static final int LSQUARE = 21;
  public static final int READ = 33;
  public static final int RSQUARE = 22;
  public static final int CHARCONST = 24;
  public static final int WHILE = 30;
  public static final int LES = 38;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 42;
  public static final int BOOLCONST = 25;
  public static final int PROG = 2;
  public static final int DEC = 45;
  public static final int ELIPSIS = 48;
  public static final int PRINT = 9;
  public static final int DO = 29;
  public static final int LEA = 39;
}

